name: 'Deploy website'

on: [push]

jobs:
  build:
    runs-on: ubuntu-22.04
    if: ${{ contains(github.event.head_commit.message, '--deploy') }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
      - name: Setup node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18
      - name: Install dependencies
        run: npm install
      - name: Build
        run: npm run build
        env:
          NODE_ENV: production
      - name: Add to subtree
        run: git add dist && git commit -m 'adding dist subtree'
      - name: Deploy to GitHub-Pages
        run: git subtree push --prefix dist origin gh-pages